# Generated by Django 2.2.13 on 2020-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0002_auto_20200822_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='app_id',
            field=models.CharField(max_length=40, null=True, verbose_name='id приложения'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user_id',
            field=models.CharField(max_length=40, null=True, verbose_name='id пользователя vk'),
        ),
    ]
